config-version: 6

# Extras:
# PokemonProperties for pokegive and developers:
# - `aggression-bias=<value>`: Used to increase the likelihood of a pokemon attacking or fleeing
# - `aggression-rate=<value>`: Used to modify how quickly the Pokemon is pushed to attacking/fleeing
# - 'fof-damage`: Used to modify the damage of a Pokemon
# - 'fof-player-only`: Used to force the pokemon to only target Players

# Exp multiplier when defeating pokemon outside of battle
world-exp-multiplier: 1.0

# Pokemon normally provide exp and EVs when defeated outside of battle. This disabled that.
disable-rewards-outside-battle: false

# High values mean less aggression. Low values mean more aggressive.
# Set to -1 to make it make wild mobs passive.
standard-aggression-timer-ticks: 3600

# Set to true to disable player-owned pokemon from being aggressive without provocation
owned-pokemon-aggression-disabled: false

# This will be applied to all damage instances of aggressive damage! Does not affect in-battle, only FoF attacks.
universal-damage-modifier: 1.0

# Set to true to disable the PokeWand from targeting other players
disable-wand-on-players: false

#Attack/Flee bias when angered. Low values = more likely to attack. High values = more likely to flee. Try not changing this by more than +/- 2.
fight-or-flight-bias: 0.0

# aggression is disabled for these pokemon
aggression-disabled-pokemon:
  species-list:
    - fakepokemonname
  aspect-tags:
    - shiny

command-usage-delay-seconds: 300

# These wild pokemon cant be targeted
# So in this example, wild shiny pokemon cannot be targetted via wands or by random aggression from other pokemon
# Shiny pokemon with owners will work as normal
protected-pokemon:
  aspect-tags:
    - shiny

# These worlds have this mod turned off.
disabled:
  worlds:
    - minecraft:example_world

Messages:
  pokewand:
    targeted: "<gold>[Target Selected]"
    detargeted: "<gray>[Called Off Pokemon]"
    received: "<green>You have received a <yellow>PokeWand<green>!"
    cooldown: "<red>You are still on cooldown for {duration}!"

# PokeWand
# Player wands will update when they login or interact with the old wands
pokewand:
  item: "minecraft:bone"
  customModelData: 0
  name: "<yellow>PokeWand"
  lore:
    - "Right click to target a pokemon!"

# These are the stats used for non-pokemon entities.
# Type effectiveness is completely ignored for these entities.
# "default" will be used for any entity that isnt listed.
# MEW is a nice baseline as it has average defensive and offensive stats dont matter.
entity-to-pokemon:
  minecraft:cow:
    pokemon: "MEW lvl=10"
  minecraft:chicken:
    pokemon: "MEW lvl=10"
  minecraft:sheep:
    pokemon: "MEW lvl=10"
  minecraft:ender_dragon:
    pokemon: "ARCEUS lvl=100"
  default:
    pokemon: "MEW lvl=50"
